# Generated by Django 3.0.3 on 2020-03-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipgate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2token',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='refresh_token',
            field=models.TextField(),
        ),
    ]
