# Generated by Django 3.0.3 on 2020-03-04 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('realname', models.CharField(blank=True, max_length=200, null=True)),
                ('host', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snom.PhoneType')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=200)),
                ('phone_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snom.PhoneType')),
            ],
        ),
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=200)),
                ('phone_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snom.PhoneType')),
            ],
        ),
    ]
