# Generated by Django 3.0.3 on 2020-02-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(max_length=12)),
                ('mac_address', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=200, blank=True, null=True)),
                ('password', models.CharField(max_length=200, blank=True, null=True)),
            ],
        ),
    ]
