# Generated by Django 3.0.7 on 2020-06-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='device',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
