# Generated by Django 3.0.3 on 2020-03-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
