# Generated by Django 3.0.3 on 2020-03-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snom', '0002_auto_20200302_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='host',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='outboundUrl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='pname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='realname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='uid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
