# Generated by Django 3.0.3 on 2020-03-13 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snom', '0002_functionkeys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionkeys',
            name='phone',
        ),
        migrations.AddField(
            model_name='functionkeys',
            name='phone_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snom.Phone'),
        ),
    ]
