# Generated by Django 3.0.7 on 2020-07-02 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snom', '0002_phone_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snom.Phone')),
                ('phone_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snom.PhoneType')),
            ],
        ),
    ]
