# Generated by Django 3.0.3 on 2020-03-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snom', '0003_auto_20200313_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionkeys',
            name='fkey0',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='functionkeys',
            name='fkey10',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='functionkeys',
            name='fkey11',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='functionkeys',
            name='fkey2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='functionkeys',
            name='fkey3',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='functionkeys',
            name='fkey4',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='functionkeys',
            name='fkey5',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='functionkeys',
            name='fkey6',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='functionkeys',
            name='fkey7',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='functionkeys',
            name='fkey8',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='functionkeys',
            name='fkey9',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='functionkeys',
            name='fkey1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
