# Generated by Django 3.0.3 on 2020-03-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snom', '0003_auto_20200302_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='outboundUrl',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='pname',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='uid',
        ),
    ]
