# Generated by Django 3.0.3 on 2020-03-13 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snom', '0004_auto_20200313_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='functionkeys',
            old_name='fkey0',
            new_name='fkey',
        ),
        migrations.RenameField(
            model_name='functionkeys',
            old_name='fkey1',
            new_name='function',
        ),
        migrations.RemoveField(
            model_name='functionkeys',
            name='fkey10',
        ),
        migrations.RemoveField(
            model_name='functionkeys',
            name='fkey11',
        ),
        migrations.RemoveField(
            model_name='functionkeys',
            name='fkey2',
        ),
        migrations.RemoveField(
            model_name='functionkeys',
            name='fkey3',
        ),
        migrations.RemoveField(
            model_name='functionkeys',
            name='fkey4',
        ),
        migrations.RemoveField(
            model_name='functionkeys',
            name='fkey5',
        ),
        migrations.RemoveField(
            model_name='functionkeys',
            name='fkey6',
        ),
        migrations.RemoveField(
            model_name='functionkeys',
            name='fkey7',
        ),
        migrations.RemoveField(
            model_name='functionkeys',
            name='fkey8',
        ),
        migrations.RemoveField(
            model_name='functionkeys',
            name='fkey9',
        ),
        migrations.AddField(
            model_name='phone',
            name='fkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snom.FunctionKeys'),
        ),
    ]
