# Generated by Django 3.0.7 on 2020-07-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snom', '0004_setting_perm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='perm',
            field=models.CharField(blank=True, choices=[('', 'None'), ('R', 'Read'), ('RW', 'Read/Write')], default='', max_length=2),
        ),
    ]
