# Generated by Django 3.0.3 on 2020-03-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snom', '0004_auto_20200302_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(max_length=12)),
                ('firmware', models.CharField(max_length=25)),
            ],
        ),
    ]
