# Generated by Django 3.0.3 on 2020-03-03 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snom', '0005_firmware'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='firmware',
            name='phone_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snom.PhoneType'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snom.PhoneType'),
        ),
    ]
