# Generated by Django 3.0.7 on 2020-07-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snom', '0006_auto_20200702_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionkey',
            name='number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
