# Generated by Django 3.0.3 on 2020-03-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snom', '0006_auto_20200303_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='firmware',
            field=models.CharField(max_length=200),
        ),
    ]
