# Generated by Django 3.0.8 on 2020-07-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snom', '0007_auto_20200702_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionkey',
            name='kind',
            field=models.CharField(choices=[('url', 'Action URL'), ('auto_answer', 'Auto Answer'), ('blf', 'BLF'), ('button', 'Button'), ('call_center_status', 'Call Center Status'), ('redirect', 'Call Forward'), ('cancel', 'Cancel'), ('conference', 'Conference'), ('F_DISP_CODE', 'Disposition Code'), ('dtmf', 'DTMF'), ('dest', 'Extension'), ('icom', 'Intercom'), ('ivr', 'IVR'), ('keyevent', 'Key Event'), ('line', 'Line'), ('multicast', 'Multicast'), ('ok', 'OK'), ('orbit', 'Park'), ('presence', 'Presence'), ('p2t', 'Push-to-Talk'), ('recorder', 'Record'), ('smart_transfer', 'SmartTransfer'), ('speed', 'Speed Dial'), ('transfer', 'Transfer'), ('xml', 'XML Definition'), ('none', 'None')], default='', max_length=20),
        ),
    ]
