# Generated by Django 3.0.8 on 2020-07-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snom', '0009_auto_20200707_1422'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='functionkey',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='functionkey',
            constraint=models.UniqueConstraint(fields=('phone', 'fkey'), name='unique_fkey'),
        ),
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.UniqueConstraint(fields=('phone_type', 'phone', 'key'), name='unique_setting'),
        ),
    ]
