# Generated by Django 3.0.8 on 2020-07-14 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snom', '0010_auto_20200713_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='phone_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snom.PhoneType'),
        ),
        migrations.AlterField(
            model_name='language',
            name='phone_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snom.PhoneType'),
        ),
    ]
