# Generated by Django 3.0.8 on 2020-07-17 10:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("snom", "0011_auto_20200714_1520"),
    ]

    operations = [
        migrations.AddField(
            model_name="phone",
            name="last_ip",
            field=models.GenericIPAddressField(default="127.0.0.1", unpack_ipv4=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phone",
            name="last_seen",
            field=models.DateTimeField(
                default=datetime.datetime(1970, 1, 1, 0, 0, 0, 0, tzinfo=utc)
            ),
            preserve_default=False,
        ),
    ]
