# Generated by Django 3.0.3 on 2020-02-25 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saps.Device')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saps.Phone')),
            ],
        ),
    ]
