# Generated by Django 3.0.3 on 2020-02-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saps', '0002_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='mac_address',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
