# Generated by Django 3.0.3 on 2020-02-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saps', '0004_oauth2token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauth2token',
            options={'verbose_name': 'OAuth2Token', 'verbose_name_plural': 'OAuth2Tokens'},
        ),
    ]
